spring.application.name=online-examination-system

#spring.datasource.url=jdbc:postgresql://localhost:5432/online_examination_db
spring.datasource.url=jdbc:postgresql://postgres:5432/online_examination_db

spring.datasource.username=postgres
spring.datasource.password=Abhay@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=9096

jwt.secret=onlineExaminationSystemSecretKeyForJwtAuthentication123456
jwt.expiration=3600000

logging.level.com.example.onlineexamination=INFO
logging.file.name=online-examination.log